[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
tokio = { version = "1.52.3", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tokio-postgres = "0.7.18"
postgres-openssl = "0.5.3"
openssl = "0.10.81"
dotenvy = "0.15.7"
bcrypt = "0.19.2"
jsonwebtoken = { version = "10.4.0", features = ["rust_crypto"] }
axum-extra = { version = "0.12.6", features = ["cookie"] }
chrono = "0.4"
