import type { Metadata } from "next";
import { Nunito, Quicksand } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  subsets: ["latin"],
  // Optional: Specify weights if you don't want the full variable font
  weight: ["400", "600", "700"], 
  variable: "--font-nunito",
});

const qs = Quicksand({
  subsets: ["latin"],
  // Optional: Specify weights if you don't want the full variable font
  weight: ["400", "600", "700"], 
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${qs.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
